TYPES = ((0, 'archa'),
         (1, 'manzarali'),
         (2, 'mevali'))

STATUS = ((0, 'alo'),
          (1, 'yaxshi'),
          (2, 'qoniqarli'),
          (3, 'o`rtacha'),
          (4, 'qoniqarsiz'),
          (5, 'yomon'),
          (6, 'achinarli'))

REGIONS = (('tashkent', 'Toshkent shahri'),
           ('tashkentv', 'Toshkent viloyati'),
           ('andijan', 'Andijon viloyati'),
           ('bukhara', 'Buxoro viloyati'),
           ('fergana', 'Ferg`ona viloyati'),
           ('jizzakh', 'Jizzax viloyati'),
           ('qashkadarya', 'Qashqadaryo viloyati'),
           ('navoiy', 'Navoiy viloyati'),
           ('namangan', 'Namangan viloyati'),
           ('samarqant', 'Samarqand viloyati'),
           ('sirdaryo', 'Sirdaryo viloyati'),
           ('surxondaryo', 'Surxondaryo viloyati'),
           ('xorazm', 'Xorazm viloyati'),
           ('qoraqalpoq', 'Qoraqalpog`iston'))

CATEGORY = ((0, 'university'),
            (1, 'school'),
            (2, 'organization'),
            (3, 'office'),
            (4, 'business center'),
            (5, 'bank'),
            (6, 'zoo'),
            (7, 'garden'),
            (8, 'residence'),
            (9, 'forest'))

DISTRICT_BY_REGION = {
    'tashkent': ['Chilonzor', 'Mirobod', 'Mirzo Ulug`bek', 'Olmazor', 'Sergeli', 'Shayxontohur', 'Uchtepa',
                 'Yakkasaroy', 'Yangihayot', 'Yashnobod', 'Yunusobod', ],
    'tashkentv': ['Bekobod', 'Boʻka', 'Boʻstonliq', 'Zangiota', 'Oqqoʻrgʻon', 'Ohangaron', 'Parkent', 'Piskent',
                  'Chinoz', 'Yuqori Chirchiq', 'Yangiyoʻl', 'Oʻrta Chirchiq', 'Qibray', 'Quyi Chirchiq'],
    "andijan": ["Andijan", "Asaka", "Bo`z", "Buloqboshi", "Izboskan", "Jalalkuduk", "Marhamat", "Oltinkan", "Paxtaobod",
                "Qorasuv", "Shahrixon", "Ulug`nor", "Xonobod"],
    "bukhara": ["Alat", "Bukhara", "G`ijduvon", "Jondor", "Karakul", "Kogon", "Olot", "Peshku", "Romitan", "Shofirkon",
                "Vabkent"],
    "fergana": ["Bag`dod ", "Beshariq ", "Buvayda ", "Dang`ara ", "Farg`ona ", "Furqat ", "Qo`qon ", "Qo`rg`ontepa ",
                "Quva ", "Rishton ", "So`x ", "Toshloq ", "Uchqo`rg`on", "Yozyovon"],
    "jizzakh": ["Arnasoy", "Baxmal", "Chiroqchi", "Dustlik", "Forish", "G`allaorol", "Jizzax", "Mirzacho`l",
                "Pakhtakor", "Yangiabad", "Zarbdor", "Zafarobod "],
    "qashkadarya": ["Chirakchi", "Dehkanabad", "G‘uzor", "Kasbi", "Kitob", "Mirishkor", "Muborak", "Nishon", "Qamashi",
                    "Qarshi", "Shakhrisabz", "Shahrisabz", "Shirin", "Yakkabog‘", "Yakkabog'"],
    "namangan": ["Chortoq", "Chust", "Dexqonobod", "Kosonsoy", "Mingbuloq", "Namangan", "Norin", "Pop", "To`raqo`rg`on",
                 "Uychi", "Uygen", "Yangiobod"],
    "navoiy": ["Kiziltepa", "Konimex", "Navoiy", "Nurota", "Tomdi", "Uchkuduk", "Xatirchi", "Zarafshon", "Navbahor"],
    "samarqant": ["Bulungur", "Ishtikhon", "Jambay", "Katta-Kurgan", "Narpay", "Nurobod", "Oqdaryo", "Pakhtachi",
                  "Pastdarg‘om", "Payariq", "Samarqand", "Toyloq", "Urgut", "Yangiyer", "Yoson", "Yoshlar"],
    "surxondaryo": ["Angor", "Boysun", "Denov", "Jarqo‘rg‘on", "Qiziriq", "Muzrabot", "Oltinsoy", "Qumqo‘rg‘on",
                    "Sariosiyo", "Sherobod", "Sho‘rchi", "Termiz", "Uzun", "Qiziltepa"],
    "sirdaryo": ["Boyovut", "Gulistan", "Mirzachul", "Ohangaron", "Saykhunobod", "Sardoba", "Sharof Rashidov", "Yangi",
                 "Yaypan"],
    "xorazm": ["Bog‘ot", "Gurlan", "Khiva", "O‘zun", "Qo‘shko‘pir", "Shavat", "Urganch", "Xonqa", "Yangiariq",
               "Yangibozor", "Yangiyer"],
    'qoraqalpoq': ["Beruniy", "Chimboy", "Ellikqal'a", "Kegeyli", "Mo‘ynoq", "Nukus", "Qanliko‘l", "Qo‘ng‘irot",
                   "Qorao‘zak", "Shumanay", "Taxiatosh", "To‘rtko‘l", "Xojeli"]
}

DISTRICTS = (("Chilonzor", "Chilonzor"), ("Mirobod", "Mirobod"), ("Mirzo Ulug`bek", "Mirzo Ulug`bek"), ("Olmazor", "Olmazor"),
    ("Sergeli", "Sergeli"), ("Shayxontohur", "Shayxontohur"), ("Uchtepa", "Uchtepa"), ("Yakkasaroy", "Yakkasaroy"),
    ("Yangihayot", "Yangihayot"), ("Yashnobod", "Yashnobod"), ("Yunusobod", "Yunusobod"), ("Bekobod", "Bekobod"),
    ("Boʻka", "Boʻka"), ("Boʻstonliq", "Boʻstonliq"), ("Zangiota", "Zangiota"), ("Oqqoʻrgʻon", "Oqqoʻrgʻon"),
    ("Ohangaron", "Ohangaron"), ("Parkent", "Parkent"), ("Piskent", "Piskent"), ("Chinoz", "Chinoz"),
    ("Yuqori Chirchiq", "Yuqori Chirchiq"), ("Yangiyoʻl", "Yangiyoʻl"), ("Oʻrta Chirchiq", "Oʻrta Chirchiq"),
    ("Qibray", "Qibray"), ("Quyi Chirchiq", "Quyi Chirchiq"), ("Andijan", "Andijan"), ("Asaka", "Asaka"),
    ("Bo`z", "Bo`z"), ("Buloqboshi", "Buloqboshi"), ("Izboskan", "Izboskan"), ("Jalalkuduk", "Jalalkuduk"),
    ("Marhamat", "Marhamat"), ("Oltinkan", "Oltinkan"), ("Paxtaobod", "Paxtaobod"), ("Qorasuv", "Qorasuv"),
    ("Shahrixon", "Shahrixon"), ("Ulug`nor", "Ulug`nor"), ("Xonobod", "Xonobod"), ("Alat", "Alat"),
    ("Bukhara", "Bukhara"), ("G`ijduvon", "G`ijduvon"), ("Jondor", "Jondor"), ("Karakul", "Karakul"),
    ("Kogon", "Kogon"), ("Olot", "Olot"), ("Peshku", "Peshku"), ("Romitan", "Romitan"), ("Shofirkon", "Shofirkon"),
    ("Vabkent", "Vabkent"), ("Bag`dod ", "Bag`dod "), ("Beshariq ", "Beshariq "), ("Buvayda ", "Buvayda "),
    ("Dang`ara ", "Dang`ara "), ("Farg`ona ", "Farg`ona "), ("Furqat ", "Furqat "), ("Qo`qon ", "Qo`qon "),
    ("Qo`rg`ontepa ", "Qo`rg`ontepa "), ("Quva ", "Quva "), ("Rishton ", "Rishton "), ("So`x ", "So`x "),
    ("Toshloq ", "Toshloq "), ("Uchqo`rg`on", "Uchqo`rg`on"), ("Yozyovon", "Yozyovon"), ("Arnasoy", "Arnasoy"),
    ("Baxmal", "Baxmal"), ("Chiroqchi", "Chiroqchi"), ("Dustlik", "Dustlik"), ("Forish", "Forish"),
    ("G`allaorol", "G`allaorol"), ("Jizzax", "Jizzax"), ("Mirzacho`l", "Mirzacho`l"), ("Pakhtakor", "Pakhtakor"),
    ("Yangiabad", "Yangiabad"), ("Zarbdor", "Zarbdor"), ("Zafarobod ", "Zafarobod "), ("Chirakchi", "Chirakchi"),
    ("Dehkanabad", "Dehkanabad"), ("G‘uzor", "G‘uzor"), ("Kasbi", "Kasbi"), ("Kitob", "Kitob"),
    ("Mirishkor", "Mirishkor"), ("Muborak", "Muborak"), ("Nishon", "Nishon"), ("Qamashi", "Qamashi"),
    ("Qarshi", "Qarshi"), ("Shakhrisabz", "Shakhrisabz"), ("Shahrisabz", "Shahrisabz"), ("Shirin", "Shirin"),
    ("Yakkabog‘", "Yakkabog‘"), ("Yakkabog'", "Yakkabog'"), ("Chortoq", "Chortoq"), ("Chust", "Chust"),
    ("Dexqonobod", "Dexqonobod"), ("Kosonsoy", "Kosonsoy"), ("Mingbuloq", "Mingbuloq"), ("Namangan", "Namangan"),
    ("Norin", "Norin"), ("Pop", "Pop"), ("To`raqo`rg`on", "To`raqo`rg`on"), ("Uychi", "Uychi"), ("Uygen", "Uygen"),
    ("Yangiobod", "Yangiobod"), ("Kiziltepa", "Kiziltepa"), ("Konimex", "Konimex"), ("Navoiy", "Navoiy"),
    ("Nurota", "Nurota"), ("Tomdi", "Tomdi"), ("Uchkuduk", "Uchkuduk"), ("Xatirchi", "Xatirchi"),
    ("Zarafshon", "Zarafshon"), ("Navbahor", "Navbahor"), ("Bulungur", "Bulungur"), ("Ishtikhon", "Ishtikhon"),
    ("Jambay", "Jambay"), ("Katta-Kurgan", "Katta-Kurgan"), ("Narpay", "Narpay"), ("Nurobod", "Nurobod"),
    ("Oqdaryo", "Oqdaryo"), ("Pakhtachi", "Pakhtachi"), ("Pastdarg‘om", "Pastdarg‘om"), ("Payariq", "Payariq"),
    ("Samarqand", "Samarqand"), ("Toyloq", "Toyloq"), ("Urgut", "Urgut"), ("Yangiyer", "Yangiyer"), ("Yoson", "Yoson"),
    ("Yoshlar", "Yoshlar"), ("Angor", "Angor"), ("Boysun", "Boysun"), ("Denov", "Denov"),
    ("Jarqo‘rg‘on", "Jarqo‘rg‘on"), ("Qiziriq", "Qiziriq"), ("Muzrabot", "Muzrabot"), ("Oltinsoy", "Oltinsoy"),
    ("Qumqo‘rg‘on", "Qumqo‘rg‘on"), ("Sariosiyo", "Sariosiyo"), ("Sherobod", "Sherobod"), ("Sho‘rchi", "Sho‘rchi"),
    ("Termiz", "Termiz"), ("Uzun", "Uzun"), ("Qiziltepa", "Qiziltepa"), ("Boyovut", "Boyovut"),
    ("Gulistan", "Gulistan"), ("Mirzachul", "Mirzachul"), ("Ohangaron", "Ohangaron"), ("Saykhunobod", "Saykhunobod"),
    ("Sardoba", "Sardoba"), ("Sharof Rashidov", "Sharof Rashidov"), ("Yangi", "Yangi"), ("Yaypan", "Yaypan"),
    ("Bog‘ot", "Bog‘ot"), ("Gurlan", "Gurlan"), ("Khiva", "Khiva"), ("O‘zun", "O‘zun"), ("Qo‘shko‘pir", "Qo‘shko‘pir"),
    ("Shavat", "Shavat"), ("Urganch", "Urganch"), ("Xonqa", "Xonqa"), ("Yangiariq", "Yangiariq"),
    ("Yangibozor", "Yangibozor"), ("Yangiyer", "Yangiyer"), ("Beruniy", "Beruniy"), ("Chimboy", "Chimboy"),
    ("Ellikqal'a", "Ellikqal'a"), ("Kegeyli", "Kegeyli"), ("Mo‘ynoq", "Mo‘ynoq"), ("Nukus", "Nukus"),
    ("Qanliko‘l", "Qanliko‘l"), ("Qo‘ng‘irot", "Qo‘ng‘irot"), ("Qorao‘zak", "Qorao‘zak"), ("Shumanay", "Shumanay"),
    ("Taxiatosh", "Taxiatosh"), ("To‘rtko‘l", "To‘rtko‘l"), ("Xojeli", "Xojeli"))
